package com.revolut.testapp.util

object Constants {

    const val DEFAULT_RATE = 0.00
    const val DEFAULT_VALUE = "0"

    // currency codes
    const val AUD = "AUD"
    const val BGN = "BGN"
    const val BRL = "BRL"
    const val CAD = "CAD"
    const val CHF = "CHF"
    const val CNY = "CNY"
    const val CZK = "CZK"
    const val DKK = "DKK"
    const val EUR = "EUR"
    const val GBP = "GBP"
    const val HKD = "HKD"
    const val HRK = "HRK"
    const val HUF = "HUF"
    const val IDR = "IDR"
    const val ILS = "ILS"
    const val INR = "INR"
    const val ISK = "ISK"
    const val JPY = "JPY"
    const val KRW = "KRW"
    const val MXN = "MXN"
    const val MYR = "MYR"
    const val NOK = "NOK"
    const val NZD = "NZD"
    const val PHP = "PHP"
    const val PLN = "PLN"
    const val RON = "RON"
    const val RUB = "RUB"
    const val SEK = "SEK"
    const val SGD = "SGD"
    const val THB = "THB"
    const val TRY = "TRY"
    const val USD = "USD"
    const val ZAR = "ZAR"

    // currencyList
    const val audName = "Australian Dollar"
    const val bgnName = "Bulgarian Lev"
    const val brlName = "Brazilian Real"
    const val cadName = "Canadian Dollar"
    const val chfName = "Swiss Franc"
    const val cnyName = "Yuan Renminbi"
    const val czkName = "Czech Koruna"
    const val dkkName = "Danish Krone"
    const val eurName = "Euro"
    const val gbpName = "Pound Sterling"
    const val hkdName = "Hong Kong Dollar"
    const val hrkName = "Croatian Kuna"
    const val hufName = "Hungarian Forint"
    const val idrName = "Indonesian Rupiah"
    const val ilsName = "New Israeli Sheqel"
    const val inrName = "Indian Rupee"
    const val iskName = "Iceland Krona"
    const val jpyName = "Japanese Yen"
    const val krwName = "South Korean Won"
    const val mxnName = "Mexican Peso"
    const val myrName = "Malaysian Ringgit"
    const val nokName = "Norwegian Krone"
    const val nzdName = "New Zealand Dollar"
    const val phpName = "Philippine Peso"
    const val plnName = "Polish Zloty"
    const val ronName = "Romanian Leu"
    const val rubName = "Russian Ruble"
    const val sekName = "Swedish Krona"
    const val sgdName = "Singapore Dollar"
    const val thbName = "Thai Baht"
    const val tryName = "Turkish Lira"
    const val usdName = "US Dollar"
    const val zarName = "South African Rand"
}
